MODEL:
  NUM_CLASSES: 4
  BACKBONE:
    NAME: enrich_vgg
    OUT_CHANNELS: (512, 1024, 512, 256)
  PRIORS:
    FEATURE_MAPS: [64, 32, 16, 8]
    STRIDES: [8, 16, 32, 64]
#    MIN_SIZES: [35.84, 76.8, 153.6, 230.4, 307.2, 384.0, 460.8]
#    MAX_SIZES: [76.8, 153.6, 230.4, 307.2, 384.0, 460.8, 537.65]
#    ASPECT_RATIOS: [[2], [2, 3], [2, 3], [2, 3], [2, 3], [2], [2]]
    MIN_SIZES: [30, 64, 128, 256]
    MAX_SIZES: [64, 128, 256, 315]
    ASPECT_RATIOS: [[2, 3], [2, 3], [2, 3], [2]]
    BOXES_PER_LOCATION: [6, 6, 6, 4]
INPUT:
  IMAGE_SIZE: 512
DATASETS:
  TRAIN: ("voc_2007_trainval",)
  TEST: ("voc_2007_test", )
SOLVER:
  MAX_ITER: 120000
  LR_STEPS: [80000, 100000]
  GAMMA: 0.1
  BATCH_SIZE: 24
  LR: 1e-4

OUTPUT_DIR: 'outputs/vgg_light_e_ssd512_voc0712'